In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

print("Libraries imported successfully!")

Libraries imported successfully!

In [2]:
df = pd.read_csv("/content/Employee_Datasetcsv")

print("Dataset loaded successfully!")

Dataset loaded successfully!

In [3]:
df.head()

,Employee_Name,Department,Attendance_Percentage,Projects_Completed,Performance_Score,Salary
0,Naina Kapoor,Finance,95.9,3,5.0,69500
1,Diya Bose,IT,86.5,6,4.7,78200
2,Abhishek Malhotra,Finance,88.9,14,5.5,86800
3,Naina Rao,Finance,89.5,7,6.5,83200
4,Kabir Shah,Operations,87.1,9,4.7,59700

In [4]:
df.shape

(250, 6)

In [5]:
df.columns

Index(['Employee_Name', 'Department', 'Attendance_Percentage',
       'Projects_Completed', 'Performance_Score', 'Salary'],
      dtype='object')

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 250 entries, 0 to 249
Data columns (total 6 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Employee_Name          250 non-null    object
 1   Department             250 non-null    object
 2   Attendance_Percentage  250 non-null    float64
 3   Projects_Completed     250 non-null    int64
 4   Performance_Score      250 non-null    float64
 5   Salary                 250 non-null    int64
dtypes: float64(2), int64(2), object(2)
memory usage: 11.8+ KB

In [7]:
df.describe()

,Attendance_Percentage,Projects_Completed,Performance_Score,Salary
count,250.000000,250.000000,250.000000,250.0000
mean,87.753200,7.032000,5.041200,74286.4000
std,6.077387,2.680994,0.826629,9033.3727
min,72.000000,2.000000,2.700000,46400.0000
25%,83.650000,5.000000,4.500000,68200.0000
50%,88.250000,7.000000,5.000000,73800.0000
75%,92.000000,9.000000,5.600000,79475.0000
max,100.000000,15.000000,7.800000,98300.0000